### ISSUE TITLE
Running the Flask Application in Windows 10 does not work according to Flatiron instructions.

### ISSUE THREAD

**Issue by kjspring** [learn-co-curriculum/dsc-flask-intro#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5318/pages/introduction-to-flask?module_item_id=423128

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
export FLASK_ENV=development
env FLASK_APP=app.py flask run

'export' is not recognized as an internal or external command, operable program or batch file. 
```

### Concern

Get an error as above.

## (Optional) Proposed Solution

This solution works.

```
set FLASK_ENV=development
set FLASK_APP=app.py
flask run
```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
addressed with #2 and implemented in [6a2d6dd](https://github.com/learn-co-curriculum/dsc-flask-intro/commit/6a2d6dd8ef581f85fb7c9183a9fbceba346e606c)
